#!/bin/sh
set -e

export CONSUL_SHARE_DIR="/var/packages/$SYNOPKG_PKGNAME/shares/consul"
mkdir -p "${CONSUL_SHARE_DIR}/var/log/consul"
LOG_FILE="${CONSUL_SHARE_DIR}/var/log/consul/install.log"

echo "$(date --iso-8601=second) Starting postinst with: CONSUL_SHARE_DIR=${CONSUL_SHARE_DIR}" >"${LOG_FILE}"

CONSUL_WEB_UI_URL_CONFIG_FILE="/var/packages/$SYNOPKG_PKGNAME/etc/consul_web_ui_url_config"
if [ ! -z "$pkgwizard_consul_web_ui_url" ]; then
    # new install
    CONSUL_WEB_UI_URL="$pkgwizard_consul_web_ui_url"
elif [ -f "$CONSUL_WEB_UI_URL_CONFIG_FILE" ]; then
    # upgrade
    CONSUL_WEB_UI_URL=$(grep -v '^#' "$CONSUL_WEB_UI_URL_CONFIG_FILE" | grep -e "CONSUL_WEB_UI_URL" | sed -e 's/.*=//')
fi

echo "CONSUL_WEB_UI_URL=$CONSUL_WEB_UI_URL" > "$CONSUL_WEB_UI_URL_CONFIG_FILE"

if [ -f "$SYNOPKG_PKGDEST/ui/config" ]; then
    echo "$(date --iso-8601=second) Updating variables in $SYNOPKG_PKGDEST/ui/config to ${CONSUL_WEB_UI_URL}" >>"${LOG_FILE}"
    CONSUL_WEB_UI_URL=${CONSUL_WEB_UI_URL////\\/}
    sed -i "s/@CONSUL_WEB_UI_URL@/$CONSUL_WEB_UI_URL/g" "$SYNOPKG_PKGDEST/ui/config"
fi

if [ "$SYNOPKG_PKG_STATUS" = "INSTALL" ]; then
  echo "$(date --iso-8601=second) Installing Consul" >>"${LOG_FILE}"

  echo "$(date --iso-8601=second) Creating ${CONSUL_SHARE_DIR}/var/lib/consul" >>"${LOG_FILE}"
  mkdir -p "${CONSUL_SHARE_DIR}/var/lib/consul"

  echo "$(date --iso-8601=second) Creating ${CONSUL_SHARE_DIR}/etc/consul.d" >>"${LOG_FILE}"
  mkdir -p "${CONSUL_SHARE_DIR}/etc/consul.d"

  CONSUL_CONFIG_FILE="${CONSUL_SHARE_DIR}/etc/consul.d/consul.hcl"
  rm -rf "${CONSUL_CONFIG_FILE}"

  SYNOLOGY_IP=$(ip route get "$(ip route show 0.0.0.0/0 | grep -oP 'via \K\S+')" | grep -oP 'src \K\S+')

  if [ ! -f "${CONSUL_CONFIG_FILE}" ]; then
    cat <<EOF > "${CONSUL_CONFIG_FILE}"
data_dir="${CONSUL_SHARE_DIR}/var/lib/consul"
client_addr = "0.0.0.0"
ui_config {
    enabled = true
}
server = true
bootstrap_expect = 1
enable_syslog = true
bind_addr = "${SYNOLOGY_IP}"
EOF
    echo "$(date --iso-8601=second) Completed creation of ${CONSUL_SHARE_DIR}/etc/consul.d" >>"${LOG_FILE}"
  else
    echo "$(date --iso-8601=second) Skip creating ${CONSUL_CONFIG_FILE} due to existing file." >>"${LOG_FILE}"
  fi;
fi;

echo "$(date --iso-8601=second) Installation complete" >>"${LOG_FILE}"

exit 0
