#!/bin/bash

PKG_NAME="${PKG_NAME:-nomad}"
case "$1" in
    start)
        synosystemctl start "pkg-${PKG_NAME}"
        ;;
    stop)
        synosystemctl stop "pkg-${PKG_NAME}"
        ;;
    status)
        synosystemctl get-active-status "pkg-${PKG_NAME}"
        ;;
    log)
        echo ""
        ;;
    *)
        echo "Usage: $0 {start|stop|status}" >&2
        exit 1
        ;;
esac
